name: one
description: A privacy-first, open-source dialer for android.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  permission_handler: ^12.0.1
  riverpod_annotation: ^3.0.3
  shadcn_ui: ^0.39.2

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  generate: true
  uses-material-design: true
